/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.group4.ui;

/**
 *
 * @author Kam
 */
public class MyAchievementUI extends javax.swing.JPanel {

    /**
     * Creates new form MyAchievementUI
     */
    public MyAchievementUI() {
        initComponents();
        init();
    }

    //添加成就条目
    private void init(){
        add(new AchievementItem(AchievementItem.STAY_UP_LATE));
        add(new AchievementItem(AchievementItem.TRY_AND_TRY));
        add(new AchievementItem(AchievementItem.ONE_SHOT));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
