/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.group4.ui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.group4.datechooser.DateChooser;
import org.group4.util.Context;

/**
 *
 * @author Kam
 */
public class MyHistoryUI extends javax.swing.JPanel {

    private Date startDate, endDate;
    /**
     * Creates new form MyHistoryUI
     */
    public MyHistoryUI() {
        initComponents();
    }
    
    private void renewHistory(){
        chartPanel.removeAll();
        String[] users = new String[1];
        users[0] = Context.getUserID();
        chartPanel.add(LineChart.createAcceptedLineChart(users, startDate, endDate, "我的ACM之路"));
        chartPanel.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        chartPanel = new javax.swing.JPanel();
        chooseStart = new javax.swing.JButton();
        chooseEnd = new javax.swing.JButton();

        chooseStart.setText("点击此按钮以选择开始时间");
        chooseStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseStartActionPerformed(evt);
            }
        });

        chooseEnd.setText("点击此按钮以选择结束时间");
        chooseEnd.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseEndActionPerformed(evt);
            }
        });

        setLayout(new BorderLayout());
        buttonPanel.setLayout(new GridLayout(1,2));
        buttonPanel.add(chooseStart);
        buttonPanel.add(chooseEnd);
        
        add(buttonPanel, BorderLayout.NORTH);
        
        chartPanel.setLayout(new GridLayout(1,1));
        add(chartPanel, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseStartActionPerformed
        // TODO add your handling code here:
        DateChooser dateChooser = new DateChooser(MainFrame.getInstance());
        dateChooser.showChooser(chooseStart, 
                               chooseStart.getX() - DateChooser.width, chooseStart.getY());

        if(dateChooser.getDate() != null){
            chooseStart.setText(new SimpleDateFormat("[ yyyy年M月d日]")
                                       .format(dateChooser.getDate()));
            startDate = dateChooser.getDate();
            if(endDate != null){
                renewHistory();
            }
        }
    }//GEN-LAST:event_chooseStartActionPerformed

    private void chooseEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEndActionPerformed
        // TODO add your handling code here:
        DateChooser dateChooser = new DateChooser(MainFrame.getInstance());
        dateChooser.showChooser(chooseEnd, 
                               chooseEnd.getX() - DateChooser.width, chooseEnd.getY());

        if(dateChooser.getDate() != null){
            chooseEnd.setText(new SimpleDateFormat("[ yyyy年M月d日]")
                                       .format(dateChooser.getDate()));
            endDate = dateChooser.getDate();
            if(startDate != null){
                renewHistory();
            }
        }
    }//GEN-LAST:event_chooseEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private javax.swing.JButton chooseEnd;
    private javax.swing.JButton chooseStart;
    private javax.swing.JPanel buttonPanel;
    // End of variables declaration//GEN-END:variables
}
