/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.group4.ui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;

import javax.swing.JOptionPane;

import org.group4.datechooser.DatePanel;
import org.group4.util.FileUtil;

/**
 *
 * @author Kam
 */
public class MyHistoryUI extends javax.swing.JPanel {

	private Date startDate, endDate;
    private final String user;
    /**
     * Creates new form MyHistoryUI
     */
    public MyHistoryUI(String id) {
    	user = id;
        initComponents();
        renewChart();
    }
    
    public void renewChart(){
    	startDate.setDate(0);
    	endDate.setDate(0);
    	if(startDate.after(endDate)){
    		JOptionPane.showMessageDialog(this, "结束时间早于开始时间？你确定？", "日期设置错误", JOptionPane.WARNING_MESSAGE);
    	}else{
    		chartPanel.removeAll();
            String[] users = new String[1];
            users[0] = user;
            chartPanel.add(LineChart.createAcceptedLineChart(users, startDate, endDate, "我的ACM之路"));
            chartPanel.validate();
    	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setOpaque(false);
        buttonPanel = new javax.swing.JPanel();
        chartPanel = new javax.swing.JPanel();
        setLayout(new BorderLayout());
        buttonPanel.setLayout(new GridLayout(1,2));
		sdp = new DatePanel(startDate = FileUtil.getFirstDate(user));
		
        edp = new DatePanel(endDate = FileUtil.getLastDate(user));
        
        buttonPanel.add(sdp);
        buttonPanel.add(edp);
        
        add(buttonPanel, BorderLayout.NORTH);
        
        chartPanel.setLayout(new GridLayout(1,1));
        add(chartPanel, BorderLayout.CENTER);
        
        sdp.addChangeListener(new ItemListener(){
			@Override
			public void itemStateChanged(ItemEvent arg0) {
				// TODO Auto-generated method stub
				renewChart();
			}
        });
        edp.addChangeListener(new ItemListener(){
			@Override
			public void itemStateChanged(ItemEvent e) {
				// TODO Auto-generated method stub
				renewChart();
			}
        });
    }// GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPanel;
    private DatePanel sdp, edp;
    private javax.swing.JPanel buttonPanel;
    // End of variables declaration//GEN-END:variables
}
